In [1]:
import numpy as np

In [2]:
x = np.arange(9)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
np.split(x,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [6]:
#provide starting indicies of arr
np.split(x,[3,6])

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [9]:
b = np.arange(16).reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
#spliting the above arr horizontally & vertically
np.hsplit(b,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [11]:
np.vsplit(b,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [15]:
#can also be done by defining axis

np.split(b,2,axis=0)

#BTW default is axis=0; only for sorting axis=-1 
#So, even if axis=0 is not defined above, its fine

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [16]:
c = np.arange(5)
c

array([0, 1, 2, 3, 4])

In [18]:
np.vstack([c,c,c,c])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [20]:
np.hstack([c,c])

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [22]:
d = c.reshape(5,1)
d

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [31]:
np.hstack([d,d])
#Again, like before you can define axis

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [35]:
z = np.array([2,4])
z

array([2, 4])

In [37]:
np.stack([z,z], axis=0)

array([[2, 4],
       [2, 4]])

In [39]:
np.stack([z,z], axis=1)

array([[2, 2],
       [4, 4]])

In [57]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
#The arrays must have the same shape, 
#except in the dimension corresponding to axis 
#(the first, by default) in case of concatenation

#But when it comes to stacking arrs
#Each array must have the same shape.

np.stack([a,b], axis=0)

ValueError: all input arrays must have the same shape

In [64]:
x = np.arange(0,40,10).reshape(-1,1)  # -1 = 4
x

array([[ 0],
       [10],
       [20],
       [30]])

In [65]:
np.concatenate([x,x,x],axis=1)

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [69]:
y = np.arange(4).reshape(2,2)
y

array([[0, 1],
       [2, 3]])

In [71]:
np.tile(y,(3,2))

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]])

In [80]:
a=np.tile(np.arange(0,40,10).reshape(-1,1), (1,3))
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [81]:
b=np.tile(np.arange(0,40,10).reshape(-1,1), (3))
b

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [84]:
#broadcasting BOOOOM!!!!
a+[1,2,3]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [85]:
a+np.array([1,2,3])

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [87]:
a = np.arange(4)
b = np.arange(8).reshape(2,4)
print(a,'\n')
print(b,'\n')
a+b

[0 1 2 3] 

[[0 1 2 3]
 [4 5 6 7]] 



array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10]])

In [89]:
#It basically automatically converted the first 1D
#array in a 2D array of same direction to perform
# the nessasary operations...BUT...

a = np.arange(8).reshape(2,4)
b = np.arange(16).reshape(4,4)
print(a,'\n')
print(b,'\n')
a+b

#Now technically u expected it to convert the 1st arr
#to 4x4 like before but it will not...because RULES

#For each dimension(starting from right side)
#1. Size of dimension shd be same
#2. Size of 1 of d dimension shd be 1

[[0 1 2 3]
 [4 5 6 7]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 



ValueError: operands could not be broadcast together with shapes (2,4) (4,4) 

In [90]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [93]:
arr.ndim

1

In [103]:
arr2 = np.expand_dims(arr, axis=0)
arr2

array([[0, 1, 2, 3, 4, 5]])

In [104]:
arr2.ndim

2

In [105]:
arr3 = np.expand_dims(arr, axis=1)
arr3

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [107]:
arr3.ndim

2

In [110]:
#same can be done by
arr4 = arr3[:, np.newaxis]
arr4

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [112]:
print(arr4.ndim)
arr4.shape

3


(6, 1, 1)

In [113]:
np.squeeze(arr4)
#to remove all redundant axis

array([0, 1, 2, 3, 4, 5])

In [116]:
np.squeeze(arr4, axis=1)
#to remove specifically the 1st axis

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [141]:
#shallow vs deep copy
a = np.arange(4)
b = a.reshape(2,2)
print(a,'\n\n', b)

[0 1 2 3] 

 [[0 1]
 [2 3]]


In [142]:
a[0] = 999
a

array([999,   1,   2,   3])

In [143]:
#but because its a shallow copy
b

array([[999,   1],
       [  2,   3]])

In [144]:
np.shares_memory(a,b)

True

In [147]:
import copy
x = np.arange(4)
y = copy.deepcopy(y.reshape(2,2))
print(x,'\n\n', y)

[0 1 2 3] 

 [[0 1]
 [2 3]]


In [148]:
x[0] = 888
x

array([888,   1,   2,   3])

In [149]:
y

array([[0, 1],
       [2, 3]])

In [150]:
np.shares_memory(x,y)

False

In [151]:
#Now in Numpy...we hv VIEWS & COPY
#VIEW --> makes a shallow copy of obj
#COPY --> makes a deepcopy of the obj

r = np.arange(4)
s = r.view()
t = r.copy()

print(np.shares_memory(r,s))
print(np.shares_memory(r,t))

True
False
